### ISSUE TITLE
Add more 'question sentences'

### ISSUE THREAD

**Issue by ErykPiasecki07** [ErykPiasecki07/VerbCalc#34]
Add more of question phrases that occur at the beginning of the sentence that should be ignored like: "what's the" etc.
The code base is already here - #32. The only thing left is to expand the dataset.

**Comment by syedatif4118** [comment]
Hello! I did not understand this issue. Can you please clearly state what is to be resolved...

**Comment by ErykPiasecki07** [comment]
When you ask a mathematical question, you don't just say 'two plus two' - you rather say 'what's two plus two', or 'how much is two plus two'. There is already code that handles that (verbcalc/core/translator/symbols.py) but it only has three examples of such questions. The task is to expand this list with as much defaults for the English language as possible.

**Comment by ErykPiasecki07** [comment]
Let me know whether everything is clear and if you feel fancy taking this issue ;)

**Comment by syedatif4118** [comment]
Ok after seeing the code I understood what's going on....and thanks a lot for sharing the details.
For example like how people search questions on google for the calculation, I have to add those kinds as many as I can.

Please correct me if I am wrong.

**Comment by ErykPiasecki07** [comment]
Resolved by: #46
