### ISSUE TITLE
Allow for more advanced handling of answer sentences

### ISSUE THREAD

**Issue by ErykPiasecki07** [ErykPiasecki07/VerbCalc#42]
For now, calculate function just returns 'The result is ' + result.

One might want to localize the library, or use some custom answers, just as they might use custom phrasings of mathematical operations (which works). Therefore the beginning of the answer should be subject to some internal dictionary just like mathematical operations or question sentences.

**Comment by nandinimaheshwari7107** [comment]
Hi @ErykPiasecki07 
I would like to try this out. However, before I start, can you explain a bit about what you mean by custom answers? give me an example maybe?

**Comment by ErykPiasecki07** [comment]
Hi!

What I mean is, when you ask Siri/Google Assistant/Alexa/your mom/stranger: 'what's two plus two', they won't just always answer '4'. Sometimes they will answer 'it's 4', and sometimes 'the result is 4' etc. The task is to prepare a set of such custom answer's beginnings and make the library use it, preferably with added flag to the calculate function that could silence the full answer if someone needs pure number.

**Comment by nandinimaheshwari7107** [comment]
Got it @ErykPiasecki07.I'd like to work on it. Can you assign this issue to me?

**Comment by nandinimaheshwari7107** [comment]
Hi @ErykPiasecki07 

This is my very first issue and potential contribution to the open-source. Hence, a few questions: 
1. Where exactly is the AUTHORS file?
2. Not sure about how to extend the documentation

I'm done with the actual feature so if you could just help me with the above queries, I'll the PR.

**Comment by ErykPiasecki07** [comment]
Hi!

1. OMG, I actually forgot it! It's not my first open-source project, but first in which all people are allowed to contribute. I'll create it right away on main!

2. We have Sphinx configured, meaning Python docstrings will **automatically** be builded to docs.

**Comment by nandinimaheshwari7107** [comment]
Cool, then I'll wait once the authors' file is added and then create the PR 👍🏻

**Comment by nandinimaheshwari7107** [comment]
Hi @ErykPiasecki07 
I've raised the PR for this issue. Kindly let me know what you think ✌🏻

**Comment by nandinimaheshwari7107** [comment]
Hi!
I've raised the PR. Do let me know what you think ✌🏻

**Comment by ErykPiasecki07** [comment]
Resolved by: #47
