### ISSUE TITLE
Segregation of Data and Code

### ISSUE THREAD

**Issue by nandinimaheshwari7107** [ErykPiasecki07/VerbCalc#49]
**Is your feature request related to a problem? Please describe.**
The code currently has hard-coded data values set within it. So when we want to add new questions, or phrases, or even words to the operations list, we have to directly edit the code. But we don't have to.

**Describe the solution you'd like**
It would be better if these hard-coded values were to be input from a text file of some format so that these values can be updated without editing the code. It also makes the code cleaner and robust.

**Describe alternatives you've considered**
I propose that we use a JSON file (or any other preferable format) to get the values into the code. This separates the code from the data and if some data needs to be updated, it needs to be done in one place only. 
We can also create methods to provide an option for users to be able to define these files as well that our code will read and get the values from, much like reading a configuration or .env file.

**Comment by ErykPiasecki07** [comment]
Really great idea! JSON sounds like the best tool for the job! When working with this issue we gotta be careful with setup.py though. From my experience, sometimes adding external files to the python package can be a little bit of a pain, but I am just noobie so what do I know even. This definitely should be worked on!
